Repository suubh/React-First-Contrib, pull requests merged in 2021-10, with the labels that each got.

#10 Create Card component and Update UI
  src/App.css
  src/App.js
  src/components/card/card.js
  src/components/card/styles.css
Labels: enhancement

#12 My details added
  src/data.json
Labels: good first issue

#13 added my details in codebase
  src/data.json
Labels: good first issue, hacktoberfest-accepted

#14 changed flex margin
  package-lock.json
  src/App.css
  src/components/card/styles.css
  yarn.lock
Labels: ✨enhancement, hacktoberfest-accepted

#23 added header and footer
  src/App.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/Header.css
  src/components/Header/Header.js
Labels: ✨enhancement, hacktoberfest-accepted
